#### DON NOT REMOVE "0x" FROM THE COLOR CODES. PUT YOUR RGB COLOR CODE AFTER "0x" BUT DON'T REMOVE IT.
# Change this to the webhook url you want to send the logs to.
webhook: "your_webhook_url"
# Join embed color. Change it to any RGB color code you want the embed to be in.
joins_color: 0x046307
# Leave embed color. Change it to any RGB color code you want the embed to be in.
leaves_color: 0xFF0000
# Sever turned on embed color. Change it to any RGB color code you want the embed to be in.
server_on_color: 0x37FF21
# Sever turned off embed color. Change it to any RGB color code you want the embed to be in.
server_off_color: 0xFF1919
# Player chat embed color. Change it to any RGB color code you want the embed to be in.
chats_color: 0xFFFFFF
# Default embed color. Recommended not to change
default_color: 0xFFFFFF
# Server name
server_name: "Your server name here"